In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
titanic = pd.read_csv('titanic.csv')

In [3]:
print(titanic.shape)
titanic.head(2)

(891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [4]:
titanic.Sex.unique()

array(['male', 'female'], dtype=object)

In [5]:
titanic.Sex.replace({'male':0,'female':1},inplace=True)

In [6]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    int64  
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(6), object(4)
memory usage: 83.7+ KB


In [7]:
titanic.Age.fillna(value = titanic.Age.mean(),inplace=True)

In [8]:
titanic['FirstClass'] = [1 if x == 1 else 0 for x in titanic.Pclass]
titanic['SecondClass'] = [1 if x == 2 else 0 for x in titanic.Pclass]

In [9]:
titanic.head(15)

PassengerId  Survived  Pclass  \
0             1         0       3   
1             2         1       1   
2             3         1       3   
3             4         1       1   
4             5         0       3   
5             6         0       3   
6             7         0       1   
7             8         0       3   
8             9         1       3   
9            10         1       2   
10           11         1       3   
11           12         1       1   
12           13         0       3   
13           14         0       3   
14           15         0       3   

                                                 Name  Sex        Age  SibSp  \
0                             Braund, Mr. Owen Harris    0  22.000000      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.000000      1   
2                              Heikkinen, Miss. Laina    1  26.000000      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.000000      1   
4                            Allen, Mr. William Henry    0  35.000000      0   
5                                    Moran, Mr. James    0  29.699118      0   
6                             McCarthy, Mr. Timothy J    0  54.000000      0   
7                      Palsson, Master. Gosta Leonard    0   2.000000      3   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    1  27.000000      0   
9                 Nasser, Mrs. Nicholas (Adele Achem)    1  14.000000      1   
10                    Sandstrom, Miss. Marguerite Rut    1   4.000000      1   
11                           Bonnell, Miss. Elizabeth    1  58.000000      0   
12                     Saundercock, Mr. William Henry    0  20.000000      0   
13                        Andersson, Mr. Anders Johan    0  39.000000      1   
14               Vestrom, Miss. Hulda Amanda Adolfina    1  14.000000      0   

    Parch            Ticket     Fare Cabin Embarked  FirstClass  SecondClass  
0       0         A/5 21171   7.2500   NaN        S           0            0  
1       0          PC 17599  71.2833   C85        C           1            0  
2       0  STON/O2. 3101282   7.9250   NaN        S           0            0  
3       0            113803  53.1000  C123        S           1            0  
4       0            373450   8.0500   NaN        S           0            0  
5       0            330877   8.4583   NaN        Q           0            0  
6       0             17463  51.8625   E46        S           1            0  
7       1            349909  21.0750   NaN        S           0            0  
8       2            347742  11.1333   NaN        S           0            0  
9       0            237736  30.0708   NaN        C           0            1  
10      1           PP 9549  16.7000    G6        S           0            0  
11      0            113783  26.5500  C103        S           1            0  
12      0         A/5. 2151   8.0500   NaN        S           0            0  
13      5            347082  31.2750   NaN        S           0            0  
14      0            350406   7.8542   NaN        S           0            0

In [10]:
features = titanic[['Sex','Age','FirstClass','SecondClass']]
survival = titanic['Survived']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(features, survival, test_size=0.2)

In [12]:
scaler = StandardScaler()
train_features = scaler.fit_transform(X_train)
test_features = scaler.transform(X_test)

In [13]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_train, y_train)

0.7865168539325843

In [14]:
lr.score(X_test, y_test)

0.770949720670391

In [15]:
print(list(zip(['Sex','Age','FirstClass','SecondClass'],lr.coef_[0])))

[('Sex', 2.396005630958027), ('Age', -0.0333373423205123), ('FirstClass', 2.240112111752042), ('SecondClass', 0.9979233542241868)]


In [16]:
Jack = np.array([0.0,20.0,0.0,0.0])
Rose = np.array([1.0,17.0,1.0,0.0])
me = np.array([0.0,35.0,0.0,0.0])

In [17]:
sample_passangers = np.array([Jack,Rose,me])

In [18]:
sample_passangers = scaler.transform(sample_passangers)
print(sample_passangers)

[[-0.74242727 -0.72709226 -0.55571893 -0.51007548]
 [ 1.34693328 -0.95298596  1.79947082 -0.51007548]
 [-0.74242727  0.40237623 -0.55571893 -0.51007548]]


In [19]:
lr.predict(sample_passangers)

array([0, 1, 0], dtype=int64)

In [20]:
lr.predict_proba(sample_passangers)

array([[0.99140041, 0.00859959],
       [0.00390286, 0.99609714],
       [0.99171556, 0.00828444]])